name: CI/CD Pipeline

on:
  push:
    branches:
      - docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          echo "$PRIVATE_KEY" > ic.pem
          chmod 600 ic.pem

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: |
            ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/image-captioning
            git pull origin docker
            sudo docker build -t image_cap .
            sudo docker restart i_c
            # Additional steps for deployment, e.g., restarting the server
